#服务器配置
server:
  port: 9872
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    # 线程配置
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 400
  servlet:
    # 编码配置
    encoding:
      charset: UTF-8
      force: true

#spring配置
spring:
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 1024MB
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置日志地址
logging:
  config: classpath:log/logback_${blade.env}.xml

# mybatis
mybatis-plus:
  mapper-locations: classpath:org/springblade/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.springblade.**.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#报表配置
report:
  enabled: false
  database:
    provider:
      prefix: blade-

#knife4j配置
knife4j:
  #启用
  enable: true
  #基础认证
  basic:
    enable: false
    username: blade
    password: blade
  #增强配置
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: false
    enableHostText: http://localhost
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    language: zh_cn
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright © 2023 SpringBlade All Rights Reserved

#swagger配置信息
swagger:
  title: SpringBlade 接口文档系统
  description: SpringBlade 接口文档系统
  version: 3.7.1
  license: Powered By SpringBlade
  licenseUrl: https://bladex.cn
  terms-of-service-url: https://bladex.cn
  contact:
    name: smallchill
    email: smallchill@163.com
    url: https://gitee.com/smallc

#第三方登陆配置
social:
  enabled: false
  domain: http://127.0.0.1:1888
  oauth:
    GITHUB:
      client-id: 233************
      client-secret: 233************************************
      redirect-uri: ${social.domain}/oauth/redirect/github
    GITEE:
      client-id: 233************
      client-secret: 233************************************
      redirect-uri: ${social.domain}/oauth/redirect/gitee
    WECHAT_OPEN:
      client-id: 233************
      client-secret: 233************************************
      redirect-uri: ${social.domain}/oauth/redirect/wechat
    QQ:
      client-id: 233************
      client-secret: 233************************************
      redirect-uri: ${social.domain}/oauth/redirect/qq
    DINGTALK:
      client-id: 233************
      client-secret: 233************************************
      redirect-uri: ${social.domain}/oauth/redirect/dingtalk


#blade配置
blade:
  context:
    headers:
      allowed:
        - X-Real-IP
        - x-real-ip
        - x-forwarded-for
        - authorization
        - Authorization
        - User-Agent
        - user-agent
        - Hosthost
        - mj-lang
        - blade-auth
  token:
    #使用 @org.springblade.test.SignKeyGenerator 获取
    sign-key: DGNKKhxwzUT4vW3pIHX7TZO2v9NvZDNi
    #使用 @org.springblade.test.AesKeyGenerator 获取
    aes-key: O2BEeIv399qHQNhD6aGW8R8DEj4bqHXm
  xss:
    enabled: true
    skip-url:
      - /blade-test/**
      - /mjkj-chat/cgform-api/editData/**
      - /mjkj-chat/cgform-api/save/**
      - /mjkj-chat/chat/open/wxPay/**
  secure:
    skip-url:
      - /mjkj-chat/chat/open/**
      - /mjkj-chat/sys/sys/dict/getDictItems/**
      - /mjkj-chat/cgform-api/getData/**
      - /mjkj-chat/cgform-api/detailData/**
      - /mjkj-chat/desform-api/desform/**
      - /mjkj-chat/chat/ai/message/**
    client:
      - client-id: sword
        path-patterns:
          - /blade-sword/**
      - client-id: saber
        path-patterns:
          - /blade-saber/**
  tenant:
    column: tenant_id
    tables:
      - blade_notice
  prop:
    upload-domain: http://localhost:8888
    remote-mode: true
    remote-path: /usr/share/nginx/html
    remote-path-iis: D://iis/html
    log-mode: true
# *************** 下面是超级AI特有，不常修改的 ******************************

chatgpt:
  debug: 'true'
  chatgptModel: 'gpt-3.5-turbo-16k'
  chatgptUrl: 'https://api.openai.com/v1/chat/completions'
  # 文本长度
  chatgptMaxToken: 4096
  chatgptRequestMaxToken: 4096
  # 文本的多样性 默认是1
  chatgptTopP: 1
  #海报背景
  posterBgUrl: https://ai-chat-gpt.oss-cn-guangzhou.aliyuncs.com/poster/shareTemplate.png
  # 移除头部
  startTitleRemove: '。,；,:,：,？, ,，,\n'
  # 画图指令
  imagePromptStart: '画,帮我画,制作,帮我制作,生成,帮我生成'
  imagePromptEnd: '图片-512x512,海报-432x768,头像-200x200'
  imageStyle: 'MJ风格'

