#服务器端口
server:
  port: 9878
#mjkj专用配置
mjkj:
  excludeTable: linaaa_ #onl_,sys_,blade_ #排除表明开头
  databaseSchema: chat #数据库名称，反向生成代码用到
  generateExcludeTable: blade_*,design_*,onl_cgform_*,sys_*,design_desform_data #反向生成表结构排除表

#blade配置
blade:
  #接口配置
  api:
    # 报文加密配置
    crypto:
    # 启用报文加密配置
    enabled: true
    # 使用AesUtil.genAesKey()生成
    aes-key: "YgDAc1LCCwH2Wff99IaYxseN0K4A38bV"
    # 使用DesUtil.genDesKey()生成
    des-key: "jMVCBsFGDQr1USHo"
  #jackson配置
  jackson:
    # 支持text文本请求,与报文加密同时开启
    support-text-plain: true
  secure:
    #接口放行
    skip-url:
      - /mjkj-chat/chat/open/**
      - /mjkj-chat/sys/sys/dict/getDictItems/**
      - /mjkj-chat/cgform-api/getData/**
      - /mjkj-chat/cgform-api/detailData/**
      - /mjkj-chat/desform-api/desform/**
      - /blade-message/message/**
      - /mjkj-chat/chat/ai/level/list
      - /mjkj-chat/chat/ai/problem/list
      - /mjkj-chat-lin/**
      - /mjkj-chat-pj/**
      - /mjkj-chat-sh/chat/open/**
      - /mjkj-chat-zh/chat/open/**
      - /blade-system/**
debug: true
