export default [
  {
    label: "通用图标",
    list: [
      "iconfont iconicon_roundadd",
      "iconfont iconicon_compile",
      "iconfont iconicon_glass",
      "iconfont iconicon_roundclose",
      "iconfont iconicon_roundreduce",
      "iconfont iconicon_delete",
      "iconfont iconicon_shakehands",
      "iconfont iconicon_task_done",
      "iconfont iconicon_voipphone",
      "iconfont iconicon_safety",
      "iconfont iconicon_work",
      "iconfont iconicon_study",
      "iconfont iconicon_task",
      "iconfont iconicon_subordinate",
      "iconfont iconicon_star",
      "iconfont iconicon_setting",
      "iconfont iconicon_sms",
      "iconfont iconicon_share",
      "iconfont iconicon_secret",
      "iconfont iconicon_scan_namecard",
      "iconfont iconicon_principal",
      "iconfont iconicon_group",
      "iconfont iconicon_send",
      "iconfont iconicon_scan",
      "iconfont iconicon_search",
      "iconfont iconicon_refresh",
      "iconfont iconicon_savememo",
      "iconfont iconicon_QRcode",
      "iconfont iconicon_im_keyboard",
      "iconfont iconicon_redpacket",
      "iconfont iconicon_photo",
      "iconfont iconicon_qq",
      "iconfont iconicon_wechat",
      "iconfont iconicon_phone",
      "iconfont iconicon_namecard",
      "iconfont iconicon_notice",
      "iconfont iconicon_next_arrow",
      "iconfont iconicon_left",
      "iconfont iconicon_more",
      "iconfont iconicon_details",
      "iconfont iconicon_message",
      "iconfont iconicon_mobilephone",
      "iconfont iconicon_im_voice",
      "iconfont iconicon_GPS",
      "iconfont iconicon_ding",
      "iconfont iconicon_exchange",
      "iconfont iconicon_cspace",
      "iconfont iconicon_doc",
      "iconfont iconicon_dispose",
      "iconfont iconicon_discovery",
      "iconfont iconicon_community_line",
      "iconfont iconicon_cloud_history",
      "iconfont iconicon_coinpurse_line",
      "iconfont iconicon_airplay",
      "iconfont iconicon_at",
      "iconfont iconicon_addressbook",
      "iconfont iconicon_boss",
      "iconfont iconicon_addperson",
      "iconfont iconicon_affiliations_li",
      "iconfont iconicon_addmessage",
      "iconfont iconicon_addresslist",
      "iconfont iconicon_add",
      "iconfont icongithub",
      "iconfont icongitee2",
    ]
  },
  {
    label: "系统图标",
    list: [
      "iconfont icon-zhongyingwen",
      "iconfont icon-caidan",
      "iconfont icon-rizhi1",
      "iconfont icon-zhuti",
      "iconfont icon-suoping",
      "iconfont icon-bug",
      "iconfont icon-qq1",
      "iconfont icon-weixin1",
      "iconfont icon-shouji",
      "iconfont icon-mima",
      "iconfont icon-yonghu",
      "iconfont icon-yanzhengma",
      "iconfont icon-canshu",
      "iconfont icon-dongtai",
      "iconfont icon-iconset0265",
      "iconfont icon-shujuzhanshi2",
      "iconfont icon-tuichuquanping",
      "iconfont icon-rizhi",
      "iconfont icon-cuowutishitubiao",
      "iconfont icon-debug",
      "iconfont icon-iconset0216",
      "iconfont icon-quanxian",
      "iconfont icon-quanxian",
      "iconfont icon-shuaxin",
      "iconfont icon-bofangqi-suoping",
      "iconfont icon-quanping",
      "iconfont icon-navicon",
      "iconfont icon-biaodan",
      "iconfont icon-liuliangyunpingtaitubiao08",
      "iconfont icon-caidanguanli",
      "iconfont icon-cuowu",
      "iconfont icon-wxbgongju",
      "iconfont icon-tuichu",
      "iconfont icon-daohanglanmoshi02",
      "iconfont icon-changyonglogo27",
      "iconfont icon-biaoge",
      "iconfont icon-baidu1",
      "iconfont icon-tubiao",
      "iconfont icon-souhu",
      "iconfont icon-msnui-360",
      "iconfont icon-iframe",
      "iconfont icon-huanyingye",
    ]
  },
  {
    label: "element-ui",
    list: [
      'el-icon-platform-eleme',
      'el-icon-eleme',
      'el-icon-delete-solid',
      'el-icon-delete',
      'el-icon-s-tools',
      'el-icon-setting',
      'el-icon-user-solid',
      'el-icon-user',
      'el-icon-phone',
      'el-icon-phone-outline',
      'el-icon-more',
      'el-icon-more-outline',
      'el-icon-star-on',
      'el-icon-star-off',
      'el-icon-s-goods',
      'el-icon-goods',
      'el-icon-warning',
      'el-icon-warning-outline',
      'el-icon-question',
      'el-icon-info',
      'el-icon-remove',
      'el-icon-circle-plus',
      'el-icon-success',
      'el-icon-error',
      'el-icon-zoom-in',
      'el-icon-zoom-out',
      'el-icon-remove-outline',
      'el-icon-circle-plus-outline',
      'el-icon-circle-check',
      'el-icon-circle-close',
      'el-icon-s-help',
      'el-icon-help',
      'el-icon-minus',
      'el-icon-plus',
      'el-icon-check',
      'el-icon-close',
      'el-icon-picture',
      'el-icon-picture-outline',
      'el-icon-picture-outline-round',
      'el-icon-upload',
      'el-icon-upload2',
      'el-icon-download',
      'el-icon-camera-solid',
      'el-icon-camera',
      'el-icon-video-camera-solid',
      'el-icon-video-camera',
      'el-icon-message-solid',
      'el-icon-bell',
      'el-icon-s-cooperation',
      'el-icon-s-order',
      'el-icon-s-platform',
      'el-icon-s-fold',
      'el-icon-s-unfold',
      'el-icon-s-operation',
      'el-icon-s-promotion',
      'el-icon-s-home',
      'el-icon-s-release',
      'el-icon-s-ticket',
      'el-icon-s-management',
      'el-icon-s-open',
      'el-icon-s-shop',
      'el-icon-s-marketing',
      'el-icon-s-flag',
      'el-icon-s-comment',
      'el-icon-s-finance',
      'el-icon-s-claim',
      'el-icon-s-custom',
      'el-icon-s-opportunity',
      'el-icon-s-data',
      'el-icon-s-check',
      'el-icon-s-grid',
      'el-icon-menu',
      'el-icon-share',
      'el-icon-d-caret',
      'el-icon-caret-left',
      'el-icon-caret-right',
      'el-icon-caret-bottom',
      'el-icon-caret-top',
      'el-icon-bottom-left',
      'el-icon-bottom-right',
      'el-icon-back',
      'el-icon-right',
      'el-icon-bottom',
      'el-icon-top',
      'el-icon-top-left',
      'el-icon-top-right',
      'el-icon-arrow-left',
      'el-icon-arrow-right',
      'el-icon-arrow-down',
      'el-icon-arrow-up',
      'el-icon-d-arrow-left',
      'el-icon-d-arrow-right',
      'el-icon-video-pause',
      'el-icon-video-play',
      'el-icon-refresh',
      'el-icon-refresh-right',
      'el-icon-refresh-left',
      'el-icon-finished',
      'el-icon-sort',
      'el-icon-sort-up',
      'el-icon-sort-down',
      'el-icon-rank',
      'el-icon-loading',
      'el-icon-view',
      'el-icon-c-scale-to-original',
      'el-icon-date',
      'el-icon-edit',
      'el-icon-edit-outline',
      'el-icon-folder',
      'el-icon-folder-opened',
      'el-icon-folder-add',
      'el-icon-folder-remove',
      'el-icon-folder-delete',
      'el-icon-folder-checked',
      'el-icon-tickets',
      'el-icon-document-remove',
      'el-icon-document-delete',
      'el-icon-document-copy',
      'el-icon-document-checked',
      'el-icon-document',
      'el-icon-document-add',
      'el-icon-printer',
      'el-icon-paperclip',
      'el-icon-takeaway-box',
      'el-icon-search',
      'el-icon-monitor',
      'el-icon-attract',
      'el-icon-mobile',
      'el-icon-scissors',
      'el-icon-umbrella',
      'el-icon-headset',
      'el-icon-brush',
      'el-icon-mouse',
      'el-icon-coordinate',
      'el-icon-magic-stick',
      'el-icon-reading',
      'el-icon-data-line',
      'el-icon-data-board',
      'el-icon-pie-chart',
      'el-icon-data-analysis',
      'el-icon-collection-tag',
      'el-icon-film',
      'el-icon-suitcase',
      'el-icon-suitcase-1',
      'el-icon-receiving',
      'el-icon-collection',
      'el-icon-files',
      'el-icon-notebook-1',
      'el-icon-notebook-2',
      'el-icon-toilet-paper',
      'el-icon-office-building',
      'el-icon-school',
      'el-icon-table-lamp',
      'el-icon-house',
      'el-icon-no-smoking',
      'el-icon-smoking',
      'el-icon-shopping-cart-full',
      'el-icon-shopping-cart-1',
      'el-icon-shopping-cart-2',
      'el-icon-shopping-bag-1',
      'el-icon-shopping-bag-2',
      'el-icon-sold-out',
      'el-icon-sell',
      'el-icon-present',
      'el-icon-box',
      'el-icon-bank-card',
      'el-icon-money',
      'el-icon-coin',
      'el-icon-wallet',
      'el-icon-discount',
      'el-icon-price-tag',
      'el-icon-news',
      'el-icon-guide',
      'el-icon-male',
      'el-icon-female',
      'el-icon-thumb',
      'el-icon-cpu',
      'el-icon-link',
      'el-icon-connection',
      'el-icon-open',
      'el-icon-turn-off',
      'el-icon-set-up',
      'el-icon-chat-round',
      'el-icon-chat-line-round',
      'el-icon-chat-square',
      'el-icon-chat-dot-round',
      'el-icon-chat-dot-square',
      'el-icon-chat-line-square',
      'el-icon-message',
      'el-icon-postcard',
      'el-icon-position',
      'el-icon-turn-off-microphone',
      'el-icon-microphone',
      'el-icon-close-notification',
      'el-icon-bangzhu',
      'el-icon-time',
      'el-icon-odometer',
      'el-icon-crop',
      'el-icon-aim',
      'el-icon-switch-button',
      'el-icon-full-screen',
      'el-icon-copy-document',
      'el-icon-mic',
      'el-icon-stopwatch',
      'el-icon-medal-1',
      'el-icon-medal',
      'el-icon-trophy',
      'el-icon-trophy-1',
      'el-icon-first-aid-kit',
      'el-icon-discover',
      'el-icon-place',
      'el-icon-location',
      'el-icon-location-outline',
      'el-icon-location-information',
      'el-icon-add-location',
      'el-icon-delete-location',
      'el-icon-map-location',
      'el-icon-alarm-clock',
      'el-icon-timer',
      'el-icon-watch-1',
      'el-icon-watch',
      'el-icon-lock',
      'el-icon-unlock',
      'el-icon-key',
      'el-icon-service',
      'el-icon-mobile-phone',
      'el-icon-bicycle',
      'el-icon-truck',
      'el-icon-ship',
      'el-icon-basketball',
      'el-icon-football',
      'el-icon-soccer',
      'el-icon-baseball',
      'el-icon-wind-power',
      'el-icon-light-rain',
      'el-icon-lightning',
      'el-icon-heavy-rain',
      'el-icon-sunrise',
      'el-icon-sunrise-1',
      'el-icon-sunset',
      'el-icon-sunny',
      'el-icon-cloudy',
      'el-icon-partly-cloudy',
      'el-icon-cloudy-and-sunny',
      'el-icon-moon',
      'el-icon-moon-night',
      'el-icon-dish',
      'el-icon-dish-1',
      'el-icon-food',
      'el-icon-chicken',
      'el-icon-fork-spoon',
      'el-icon-knife-fork',
      'el-icon-burger',
      'el-icon-tableware',
      'el-icon-sugar',
      'el-icon-dessert',
      'el-icon-ice-cream',
      'el-icon-hot-water',
      'el-icon-water-cup',
      'el-icon-coffee-cup',
      'el-icon-cold-drink',
      'el-icon-goblet',
      'el-icon-goblet-full',
      'el-icon-goblet-square',
      'el-icon-goblet-square-full',
      'el-icon-refrigerator',
      'el-icon-grape',
      'el-icon-watermelon',
      'el-icon-cherry',
      'el-icon-apple',
      'el-icon-pear',
      'el-icon-orange',
      'el-icon-coffee',
      'el-icon-ice-tea',
      'el-icon-ice-drink',
      'el-icon-milk-tea',
      'el-icon-potato-strips',
      'el-icon-lollipop',
      'el-icon-ice-cream-square',
      'el-icon-ice-cream-round',
    ],
  },
  {
    label: "fontawesome",
    list: [
      "fa fa-glass",
      "fa fa-music",
      "fa fa-search",
      "fa fa-envelope-o",
      "fa fa-heart",
      "fa fa-star",
      "fa fa-star-o",
      "fa fa-user",
      "fa fa-film",
      "fa fa-th-large",
      "fa fa-th",
      "fa fa-th-list",
      "fa fa-check",
      "fa fa-remove",
      "fa fa-close",
      "fa fa-times",
      "fa fa-search-plus",
      "fa fa-search-minus",
      "fa fa-power-off",
      "fa fa-signal",
      "fa fa-gear",
      "fa fa-cog",
      "fa fa-trash-o",
      "fa fa-home",
      "fa fa-file-o",
      "fa fa-clock-o",
      "fa fa-road",
      "fa fa-download",
      "fa fa-arrow-circle-o-down",
      "fa fa-arrow-circle-o-up",
      "fa fa-inbox",
      "fa fa-play-circle-o",
      "fa fa-rotate-right",
      "fa fa-repeat",
      "fa fa-refresh",
      "fa fa-list-alt",
      "fa fa-lock",
      "fa fa-flag",
      "fa fa-headphones",
      "fa fa-volume-off",
      "fa fa-volume-down",
      "fa fa-volume-up",
      "fa fa-qrcode",
      "fa fa-barcode",
      "fa fa-tag",
      "fa fa-tags",
      "fa fa-book",
      "fa fa-bookmark",
      "fa fa-print",
      "fa fa-camera",
      "fa fa-font",
      "fa fa-bold",
      "fa fa-italic",
      "fa fa-text-height",
      "fa fa-text-width",
      "fa fa-align-left",
      "fa fa-align-center",
      "fa fa-align-right",
      "fa fa-align-justify",
      "fa fa-list",
      "fa fa-dedent",
      "fa fa-outdent",
      "fa fa-indent",
      "fa fa-video-camera",
      "fa fa-photo",
      "fa fa-image",
      "fa fa-picture-o",
      "fa fa-pencil",
      "fa fa-map-marker",
      "fa fa-adjust",
      "fa fa-tint",
      "fa fa-edit",
      "fa fa-pencil-square-o",
      "fa fa-share-square-o",
      "fa fa-check-square-o",
      "fa fa-arrows",
      "fa fa-step-backward",
      "fa fa-fast-backward",
      "fa fa-backward",
      "fa fa-play",
      "fa fa-pause",
      "fa fa-stop",
      "fa fa-forward",
      "fa fa-fast-forward",
      "fa fa-step-forward",
      "fa fa-eject",
      "fa fa-chevron-left",
      "fa fa-chevron-right",
      "fa fa-plus-circle",
      "fa fa-minus-circle",
      "fa fa-times-circle",
      "fa fa-check-circle",
      "fa fa-question-circle",
      "fa fa-info-circle",
      "fa fa-crosshairs",
      "fa fa-times-circle-o",
      "fa fa-check-circle-o",
      "fa fa-ban",
      "fa fa-arrow-left",
      "fa fa-arrow-right",
      "fa fa-arrow-up",
      "fa fa-arrow-down",
      "fa fa-mail-forward",
      "fa fa-share",
      "fa fa-expand",
      "fa fa-compress",
      "fa fa-plus",
      "fa fa-minus",
      "fa fa-asterisk",
      "fa fa-exclamation-circle",
      "fa fa-gift",
      "fa fa-leaf",
      "fa fa-fire",
      "fa fa-eye",
      "fa fa-eye-slash",
      "fa fa-warning",
      "fa fa-exclamation-triangle",
      "fa fa-plane",
      "fa fa-calendar",
      "fa fa-random",
      "fa fa-comment",
      "fa fa-magnet",
      "fa fa-chevron-up",
      "fa fa-chevron-down",
      "fa fa-retweet",
      "fa fa-shopping-cart",
      "fa fa-folder",
      "fa fa-folder-open",
      "fa fa-arrows-v",
      "fa fa-arrows-h",
      "fa fa-bar-chart-o",
      "fa fa-bar-chart",
      "fa fa-twitter-square",
      "fa fa-facebook-square",
      "fa fa-camera-retro",
      "fa fa-key",
      "fa fa-gears",
      "fa fa-cogs",
      "fa fa-comments",
      "fa fa-thumbs-o-up",
      "fa fa-thumbs-o-down",
      "fa fa-star-half",
      "fa fa-heart-o",
      "fa fa-sign-out",
      "fa fa-linkedin-square",
      "fa fa-thumb-tack",
      "fa fa-external-link",
      "fa fa-sign-in",
      "fa fa-trophy",
      "fa fa-github-square",
      "fa fa-upload",
      "fa fa-lemon-o",
      "fa fa-phone",
      "fa fa-square-o",
      "fa fa-bookmark-o",
      "fa fa-phone-square",
      "fa fa-twitter",
      "fa fa-facebook-f",
      "fa fa-facebook",
      "fa fa-github",
      "fa fa-unlock",
      "fa fa-credit-card",
      "fa fa-feed",
      "fa fa-rss",
      "fa fa-hdd-o",
      "fa fa-bullhorn",
      "fa fa-bell",
      "fa fa-certificate",
      "fa fa-hand-o-right",
      "fa fa-hand-o-left",
      "fa fa-hand-o-up",
      "fa fa-hand-o-down",
      "fa fa-arrow-circle-left",
      "fa fa-arrow-circle-right",
      "fa fa-arrow-circle-up",
      "fa fa-arrow-circle-down",
      "fa fa-globe",
      "fa fa-wrench",
      "fa fa-tasks",
      "fa fa-filter",
      "fa fa-briefcase",
      "fa fa-arrows-alt",
      "fa fa-group",
      "fa fa-users",
      "fa fa-chain",
      "fa fa-link",
      "fa fa-cloud",
      "fa fa-flask",
      "fa fa-cut",
      "fa fa-scissors",
      "fa fa-copy",
      "fa fa-files-o",
      "fa fa-paperclip",
      "fa fa-save",
      "fa fa-floppy-o",
      "fa fa-square",
      "fa fa-navicon",
      "fa fa-reorder",
      "fa fa-bars",
      "fa fa-list-ul",
      "fa fa-list-ol",
      "fa fa-strikethrough",
      "fa fa-underline",
      "fa fa-table",
      "fa fa-magic",
      "fa fa-truck",
      "fa fa-pinterest",
      "fa fa-pinterest-square",
      "fa fa-google-plus-square",
      "fa fa-google-plus",
      "fa fa-money",
      "fa fa-caret-down",
      "fa fa-caret-up",
      "fa fa-caret-left",
      "fa fa-caret-right",
      "fa fa-columns",
      "fa fa-unsorted",
      "fa fa-sort",
      "fa fa-sort-down",
      "fa fa-sort-desc",
      "fa fa-sort-up",
      "fa fa-sort-asc",
      "fa fa-envelope",
      "fa fa-linkedin",
      "fa fa-rotate-left",
      "fa fa-undo",
      "fa fa-legal",
      "fa fa-gavel",
      "fa fa-dashboard",
      "fa fa-tachometer",
      "fa fa-comment-o",
      "fa fa-comments-o",
      "fa fa-flash",
      "fa fa-bolt",
      "fa fa-sitemap",
      "fa fa-umbrella",
      "fa fa-paste",
      "fa fa-clipboard",
      "fa fa-lightbulb-o",
      "fa fa-exchange",
      "fa fa-cloud-download",
      "fa fa-cloud-upload",
      "fa fa-user-md",
      "fa fa-stethoscope",
      "fa fa-suitcase",
      "fa fa-bell-o",
      "fa fa-coffee",
      "fa fa-cutlery",
      "fa fa-file-text-o",
      "fa fa-building-o",
      "fa fa-hospital-o",
      "fa fa-ambulance",
      "fa fa-medkit",
      "fa fa-fighter-jet",
      "fa fa-beer",
      "fa fa-h-square",
      "fa fa-plus-square",
      "fa fa-angle-double-left",
      "fa fa-angle-double-right",
      "fa fa-angle-double-up",
      "fa fa-angle-double-down",
      "fa fa-angle-left",
      "fa fa-angle-right",
      "fa fa-angle-up",
      "fa fa-angle-down",
      "fa fa-desktop",
      "fa fa-laptop",
      "fa fa-tablet",
      "fa fa-mobile-phone",
      "fa fa-mobile",
      "fa fa-circle-o",
      "fa fa-quote-left",
      "fa fa-quote-right",
      "fa fa-spinner",
      "fa fa-circle",
      "fa fa-mail-reply",
      "fa fa-reply",
      "fa fa-github-alt",
      "fa fa-folder-o",
      "fa fa-folder-open-o",
      "fa fa-smile-o",
      "fa fa-frown-o",
      "fa fa-meh-o",
      "fa fa-gamepad",
      "fa fa-keyboard-o",
      "fa fa-flag-o",
      "fa fa-flag-checkered",
      "fa fa-terminal",
      "fa fa-code",
      "fa fa-mail-reply-all",
      "fa fa-reply-all",
      "fa fa-star-half-empty",
      "fa fa-star-half-full",
      "fa fa-star-half-o",
      "fa fa-location-arrow",
      "fa fa-crop",
      "fa fa-code-fork",
      "fa fa-unlink",
      "fa fa-chain-broken",
      "fa fa-question",
      "fa fa-info",
      "fa fa-exclamation",
      "fa fa-superscript",
      "fa fa-subscript",
      "fa fa-eraser",
      "fa fa-puzzle-piece",
      "fa fa-microphone",
      "fa fa-microphone-slash",
      "fa fa-shield",
      "fa fa-calendar-o",
      "fa fa-fire-extinguisher",
      "fa fa-rocket",
      "fa fa-maxcdn",
      "fa fa-chevron-circle-left",
      "fa fa-chevron-circle-right",
      "fa fa-chevron-circle-up",
      "fa fa-chevron-circle-down",
      "fa fa-html5",
      "fa fa-css3",
      "fa fa-anchor",
      "fa fa-unlock-alt",
      "fa fa-bullseye",
      "fa fa-ellipsis-h",
      "fa fa-ellipsis-v",
      "fa fa-rss-square",
      "fa fa-play-circle",
      "fa fa-ticket",
      "fa fa-minus-square",
      "fa fa-minus-square-o",
      "fa fa-level-up",
      "fa fa-level-down",
      "fa fa-check-square",
      "fa fa-pencil-square",
      "fa fa-external-link-square",
      "fa fa-share-square",
      "fa fa-compass",
      "fa fa-toggle-down",
      "fa fa-caret-square-o-down",
      "fa fa-toggle-up",
      "fa fa-caret-square-o-up",
      "fa fa-toggle-right",
      "fa fa-caret-square-o-right",
      "fa fa-euro",
      "fa fa-eur",
      "fa fa-gbp",
      "fa fa-dollar",
      "fa fa-usd",
      "fa fa-rupee",
      "fa fa-inr",
      "fa fa-cny",
      "fa fa-rmb",
      "fa fa-yen",
      "fa fa-jpy",
      "fa fa-ruble",
      "fa fa-rouble",
      "fa fa-rub",
      "fa fa-won",
      "fa fa-krw",
      "fa fa-bitcoin",
      "fa fa-btc",
      "fa fa-file",
      "fa fa-file-text",
      "fa fa-sort-alpha-asc",
      "fa fa-sort-alpha-desc",
      "fa fa-sort-amount-asc",
      "fa fa-sort-amount-desc",
      "fa fa-sort-numeric-asc",
      "fa fa-sort-numeric-desc",
      "fa fa-thumbs-up",
      "fa fa-thumbs-down",
      "fa fa-youtube-square",
      "fa fa-youtube",
      "fa fa-xing",
      "fa fa-xing-square",
      "fa fa-youtube-play",
      "fa fa-dropbox",
      "fa fa-stack-overflow",
      "fa fa-instagram",
      "fa fa-flickr",
      "fa fa-adn",
      "fa fa-bitbucket",
      "fa fa-bitbucket-square",
      "fa fa-tumblr",
      "fa fa-tumblr-square",
      "fa fa-long-arrow-down",
      "fa fa-long-arrow-up",
      "fa fa-long-arrow-left",
      "fa fa-long-arrow-right",
      "fa fa-apple",
      "fa fa-windows",
      "fa fa-android",
      "fa fa-linux",
      "fa fa-dribbble",
      "fa fa-skype",
      "fa fa-foursquare",
      "fa fa-trello",
      "fa fa-female",
      "fa fa-male",
      "fa fa-gittip",
      "fa fa-gratipay",
      "fa fa-sun-o",
      "fa fa-moon-o",
      "fa fa-archive",
      "fa fa-bug",
      "fa fa-vk",
      "fa fa-weibo",
      "fa fa-renren",
      "fa fa-pagelines",
      "fa fa-stack-exchange",
      "fa fa-arrow-circle-o-right",
      "fa fa-arrow-circle-o-left",
      "fa fa-toggle-left",
      "fa fa-caret-square-o-left",
      "fa fa-dot-circle-o",
      "fa fa-wheelchair",
      "fa fa-vimeo-square",
      "fa fa-turkish-lira",
      "fa fa-try",
      "fa fa-plus-square-o",
      "fa fa-space-shuttle",
      "fa fa-slack",
      "fa fa-envelope-square",
      "fa fa-wordpress",
      "fa fa-openid",
      "fa fa-institution",
      "fa fa-bank",
      "fa fa-university",
      "fa fa-mortar-board",
      "fa fa-graduation-cap",
      "fa fa-yahoo",
      "fa fa-google",
      "fa fa-reddit",
      "fa fa-reddit-square",
      "fa fa-stumbleupon-circle",
      "fa fa-stumbleupon",
      "fa fa-delicious",
      "fa fa-digg",
      "fa fa-pied-piper-pp",
      "fa fa-pied-piper-alt",
      "fa fa-drupal",
      "fa fa-joomla",
      "fa fa-language",
      "fa fa-fax",
      "fa fa-building",
      "fa fa-child",
      "fa fa-paw",
      "fa fa-spoon",
      "fa fa-cube",
      "fa fa-cubes",
      "fa fa-behance",
      "fa fa-behance-square",
      "fa fa-steam",
      "fa fa-steam-square",
      "fa fa-recycle",
      "fa fa-automobile",
      "fa fa-car",
      "fa fa-cab",
      "fa fa-taxi",
      "fa fa-tree",
      "fa fa-spotify",
      "fa fa-deviantart",
      "fa fa-soundcloud",
      "fa fa-database",
      "fa fa-file-pdf-o",
      "fa fa-file-word-o",
      "fa fa-file-excel-o",
      "fa fa-file-powerpoint-o",
      "fa fa-file-photo-o",
      "fa fa-file-picture-o",
      "fa fa-file-image-o",
      "fa fa-file-zip-o",
      "fa fa-file-archive-o",
      "fa fa-file-sound-o",
      "fa fa-file-audio-o",
      "fa fa-file-movie-o",
      "fa fa-file-video-o",
      "fa fa-file-code-o",
      "fa fa-vine",
      "fa fa-codepen",
      "fa fa-jsfiddle",
      "fa fa-life-bouy",
      "fa fa-life-buoy",
      "fa fa-life-saver",
      "fa fa-support",
      "fa fa-life-ring",
      "fa fa-circle-o-notch",
      "fa fa-ra",
      "fa fa-resistance",
      "fa fa-rebel",
      "fa fa-ge",
      "fa fa-empire",
      "fa fa-git-square",
      "fa fa-git",
      "fa fa-y-combinator-square",
      "fa fa-yc-square",
      "fa fa-hacker-news",
      "fa fa-tencent-weibo",
      "fa fa-qq",
      "fa fa-wechat",
      "fa fa-weixin",
      "fa fa-send",
      "fa fa-paper-plane",
      "fa fa-send-o",
      "fa fa-paper-plane-o",
      "fa fa-history",
      "fa fa-circle-thin",
      "fa fa-header",
      "fa fa-paragraph",
      "fa fa-sliders",
      "fa fa-share-alt",
      "fa fa-share-alt-square",
      "fa fa-bomb",
      "fa fa-soccer-ball-o",
      "fa fa-futbol-o",
      "fa fa-tty",
      "fa fa-binoculars",
      "fa fa-plug",
      "fa fa-slideshare",
      "fa fa-twitch",
      "fa fa-yelp",
      "fa fa-newspaper-o",
      "fa fa-wifi",
      "fa fa-calculator",
      "fa fa-paypal",
      "fa fa-google-wallet",
      "fa fa-cc-visa",
      "fa fa-cc-mastercard",
      "fa fa-cc-discover",
      "fa fa-cc-amex",
      "fa fa-cc-paypal",
      "fa fa-cc-stripe",
      "fa fa-bell-slash",
      "fa fa-bell-slash-o",
      "fa fa-trash",
      "fa fa-copyright",
      "fa fa-at",
      "fa fa-eyedropper",
      "fa fa-paint-brush",
      "fa fa-birthday-cake",
      "fa fa-area-chart",
      "fa fa-pie-chart",
      "fa fa-line-chart",
      "fa fa-lastfm",
      "fa fa-lastfm-square",
      "fa fa-toggle-off",
      "fa fa-toggle-on",
      "fa fa-bicycle",
      "fa fa-bus",
      "fa fa-ioxhost",
      "fa fa-angellist",
      "fa fa-cc",
      "fa fa-shekel",
      "fa fa-sheqel",
      "fa fa-ils",
      "fa fa-meanpath",
      "fa fa-buysellads",
      "fa fa-connectdevelop",
      "fa fa-dashcube",
      "fa fa-forumbee",
      "fa fa-leanpub",
      "fa fa-sellsy",
      "fa fa-shirtsinbulk",
      "fa fa-simplybuilt",
      "fa fa-skyatlas",
      "fa fa-cart-plus",
      "fa fa-cart-arrow-down",
      "fa fa-diamond",
      "fa fa-ship",
      "fa fa-user-secret",
      "fa fa-motorcycle",
      "fa fa-street-view",
      "fa fa-heartbeat",
      "fa fa-venus",
      "fa fa-mars",
      "fa fa-mercury",
      "fa fa-intersex",
      "fa fa-transgender",
      "fa fa-transgender-alt",
      "fa fa-venus-double",
      "fa fa-mars-double",
      "fa fa-venus-mars",
      "fa fa-mars-stroke",
      "fa fa-mars-stroke-v",
      "fa fa-mars-stroke-h",
      "fa fa-neuter",
      "fa fa-genderless",
      "fa fa-facebook-official",
      "fa fa-pinterest-p",
      "fa fa-whatsapp",
      "fa fa-server",
      "fa fa-user-plus",
      "fa fa-user-times",
      "fa fa-hotel",
      "fa fa-bed",
      "fa fa-viacoin",
      "fa fa-train",
      "fa fa-subway",
      "fa fa-medium",
      "fa fa-yc",
      "fa fa-y-combinator",
      "fa fa-optin-monster",
      "fa fa-opencart",
      "fa fa-expeditedssl",
      "fa fa-battery-4",
      "fa fa-battery",
      "fa fa-battery-full",
      "fa fa-battery-3",
      "fa fa-battery-three-quarters",
      "fa fa-battery-2",
      "fa fa-battery-half",
      "fa fa-battery-1",
      "fa fa-battery-quarter",
      "fa fa-battery-0",
      "fa fa-battery-empty",
      "fa fa-mouse-pointer",
      "fa fa-i-cursor",
      "fa fa-object-group",
      "fa fa-object-ungroup",
      "fa fa-sticky-note",
      "fa fa-sticky-note-o",
      "fa fa-cc-jcb",
      "fa fa-cc-diners-club",
      "fa fa-clone",
      "fa fa-balance-scale",
      "fa fa-hourglass-o",
      "fa fa-hourglass-1",
      "fa fa-hourglass-start",
      "fa fa-hourglass-2",
      "fa fa-hourglass-half",
      "fa fa-hourglass-3",
      "fa fa-hourglass-end",
      "fa fa-hourglass",
      "fa fa-hand-grab-o",
      "fa fa-hand-rock-o",
      "fa fa-hand-stop-o",
      "fa fa-hand-paper-o",
      "fa fa-hand-scissors-o",
      "fa fa-hand-lizard-o",
      "fa fa-hand-spock-o",
      "fa fa-hand-pointer-o",
      "fa fa-hand-peace-o",
      "fa fa-trademark",
      "fa fa-registered",
      "fa fa-creative-commons",
      "fa fa-gg",
      "fa fa-gg-circle",
      "fa fa-tripadvisor",
      "fa fa-odnoklassniki",
      "fa fa-odnoklassniki-square",
      "fa fa-get-pocket",
      "fa fa-wikipedia-w",
      "fa fa-safari",
      "fa fa-chrome",
      "fa fa-firefox",
      "fa fa-opera",
      "fa fa-internet-explorer",
      "fa fa-tv",
      "fa fa-television",
      "fa fa-contao",
      "fa fa-500px",
      "fa fa-amazon",
      "fa fa-calendar-plus-o",
      "fa fa-calendar-minus-o",
      "fa fa-calendar-times-o",
      "fa fa-calendar-check-o",
      "fa fa-industry",
      "fa fa-map-pin",
      "fa fa-map-signs",
      "fa fa-map-o",
      "fa fa-map",
      "fa fa-commenting",
      "fa fa-commenting-o",
      "fa fa-houzz",
      "fa fa-vimeo",
      "fa fa-black-tie",
      "fa fa-fonticons",
      "fa fa-reddit-alien",
      "fa fa-edge",
      "fa fa-credit-card-alt",
      "fa fa-codiepie",
      "fa fa-modx",
      "fa fa-fort-awesome",
      "fa fa-usb",
      "fa fa-product-hunt",
      "fa fa-mixcloud",
      "fa fa-scribd",
      "fa fa-pause-circle",
      "fa fa-pause-circle-o",
      "fa fa-stop-circle",
      "fa fa-stop-circle-o",
      "fa fa-shopping-bag",
      "fa fa-shopping-basket",
      "fa fa-hashtag",
      "fa fa-bluetooth",
      "fa fa-bluetooth-b",
      "fa fa-percent",
      "fa fa-gitlab",
      "fa fa-wpbeginner",
      "fa fa-wpforms",
      "fa fa-envira",
      "fa fa-universal-access",
      "fa fa-wheelchair-alt",
      "fa fa-question-circle-o",
      "fa fa-blind",
      "fa fa-audio-description",
      "fa fa-volume-control-phone",
      "fa fa-braille",
      "fa fa-assistive-listening-systems",
      "fa fa-asl-interpreting",
      "fa fa-american-sign-language-interpreting",
      "fa fa-deafness",
      "fa fa-hard-of-hearing",
      "fa fa-deaf",
      "fa fa-glide",
      "fa fa-glide-g",
      "fa fa-signing",
      "fa fa-sign-language",
      "fa fa-low-vision",
      "fa fa-viadeo",
      "fa fa-viadeo-square",
      "fa fa-snapchat",
      "fa fa-snapchat-ghost",
      "fa fa-snapchat-square",
      "fa fa-pied-piper",
      "fa fa-first-order",
      "fa fa-yoast",
      "fa fa-themeisle",
      "fa fa-google-plus-circle",
      "fa fa-google-plus-official",
      "fa fa-fa",
      "fa fa-font-awesome",
      "fa fa-handshake-o",
      "fa fa-envelope-open",
      "fa fa-envelope-open-o",
      "fa fa-linode",
      "fa fa-address-book",
      "fa fa-address-book-o",
      "fa fa-vcard",
      "fa fa-address-card",
      "fa fa-vcard-o",
      "fa fa-address-card-o",
      "fa fa-user-circle",
      "fa fa-user-circle-o",
      "fa fa-user-o",
      "fa fa-id-badge",
      "fa fa-drivers-license",
      "fa fa-id-card",
      "fa fa-drivers-license-o",
      "fa fa-id-card-o",
      "fa fa-quora",
      "fa fa-free-code-camp",
      "fa fa-telegram",
      "fa fa-thermometer-4",
      "fa fa-thermometer",
      "fa fa-thermometer-full",
      "fa fa-thermometer-3",
      "fa fa-thermometer-three-quarters",
      "fa fa-thermometer-2",
      "fa fa-thermometer-half",
      "fa fa-thermometer-1",
      "fa fa-thermometer-quarter",
      "fa fa-thermometer-0",
      "fa fa-thermometer-empty",
      "fa fa-shower",
      "fa fa-bathtub",
      "fa fa-s15",
      "fa fa-bath",
      "fa fa-podcast",
      "fa fa-window-maximize",
      "fa fa-window-minimize",
      "fa fa-window-restore",
      "fa fa-times-rectangle",
      "fa fa-window-close",
      "fa fa-times-rectangle-o",
      "fa fa-window-close-o",
      "fa fa-bandcamp",
      "fa fa-grav",
      "fa fa-etsy",
      "fa fa-imdb",
      "fa fa-ravelry",
      "fa fa-eercast",
      "fa fa-microchip",
      "fa fa-snowflake-o",
      "fa fa-superpowers",
      "fa fa-wpexplorer",
      "fa fa-meetup",
    ]
  }
]
