#服务器端口
server:
  port: 9871

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888
blade:
  token:
    aes-key: YgDAc1LCCwH2Wff99IaYxseN0K4A38bVz
    sign-key: DGNKKhxwzUT4vW3pIHX7TZO2v9NvZDNi
