#服务器端口
server:
  port: 9871
#项目的启动端口号

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888
